#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# vim: expandtab sw=4 ts=4 sts=4:

# Converts home made translation system to gettext

import re
import os

matcher = re.compile('\$locale\[\'(.*)\'\] *= *\'(.*)\'')

messages = {}
matchers = {}
matchers_pure = {}

# Grab message IDs
en = file('languages/en.php')
for line in en:
    res = matcher.search(line)
    if res is None:
        continue
    id = res.groups(1)[0]
    text = res.groups(1)[1]
    messages[id] = text
    matchers[id] = re.compile('LOCALE_get\(\'%s\'\)' % id)
    matchers_pure[id] = re.compile('([^_][^(])\'%s\'' % id)
en.close()

# Convert PHP files to use gettext
for root, dirs, files in os.walk('./'):
    if root == './languages':
        continue
    for filename in files:
        ext = os.path.splitext(filename)[1]
        if ext == '.php':
            filepath = os.path.join(root, filename)
            print filepath
            cur = file(filepath, 'r')
            data = cur.read()
            cur.close()
            for id in matchers.keys():
                 data = matchers[id].sub('_(\'%s\')' % messages[id], data)
                 data = matchers_pure[id].sub('\\1_(\'%s\')' % messages[id], data)
            cur = file(filepath, 'w')
            cur.write(data)
            cur.close()

