#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# vim: expandtab sw=4 ts=4 sts=4:

# Converts home made translation system to gettext

import re
import os

matcher = re.compile('\$locale\[\'(.*)\'\] *= *\'(.*)\'')

messages = {}
messages_cs = {}

# Grab message IDs
en = file('languages/en.php')
for line in en:
    res = matcher.search(line)
    if res is None:
        continue
    id = res.groups(1)[0]
    text = res.groups(1)[1]
    messages[id] = text
en.close()

# Grab message IDs
cs = file('languages/cz.php')
for line in cs:
    res = matcher.search(line)
    if res is None:
        continue
    id = res.groups(1)[0]
    text = res.groups(1)[1]
    messages_cs[id] = text
cs.close()

# Generate po file
out = file('locale/cs/ukolovnik.po', 'w')
out.write('''
# Ukolovnik translation.
# Copyright (C) 2003 - 2007 Michal Čihař
# This file is distributed under the same license as the Ukolovnik package.
# Michal Čihař <michal@cihar.com>, 2007.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\\n"
"Report-Msgid-Bugs-To: michal@cihar.com\\n"
"POT-Creation-Date: 2007-10-11 12:00+0900\\n"
"PO-Revision-Date: 2007-10-11 12:03+0900\\n"
"Last-Translator: Michal Čihař <michal@cihar.com>\\n"
"Language-Team: Czech\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\\n"

''')

for id in messages.keys():
    out.write('msgid "%s"\n' % messages[id].replace('"', '\\"'))
    out.write('msgstr "%s"\n' % messages_cs[id].replace('"', '\\"'))
    out.write('\n')

out.close()
