#!/bin/sh
for x in locale/*/ukolovnik.po  ; do 
    lang=`echo $x | sed 's@locale/\(.*\)/ukolovnik.po@\1@'`
    echo -n "$lang: "
    mkdir -p locale-data/$lang/LC_MESSAGES
    msgfmt --statistics --check -o locale-data/$lang/LC_MESSAGES/ukolovnik.mo $x
done
