#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

# Usage: make-release [branch]

set -e

repo=ukolovnik

version=`sed -n "/version =/ s/.*= '\(.*\)'.*/\1/p" lib/version.php`

srcdir=`pwd`



dotag=0
if [ "x$1" = "xbranch" ] ; then
    checkout=HEAD
    dotag=1
    # Pre release checks
    if grep -q '^200[0-9]???? - ' ChangeLog ; then
        echo 'ChangeLog does not seem to be finalised, aborting!'
        exit 1
    fi
    shift
elif [ "x$1" = "x" ] ; then
    checkout=HEAD
else 
    checkout=$1
    version=$1
    shift
fi

tmp=`mktemp -dt $repo-build-XXXXXX`
cd $tmp
echo Working in $tmp
echo "Creating release $version from $checkout"
git clone $srcdir $repo-$version
cd $repo-$version
git checkout $checkout
rm -rf .git
./admin/locales-generate
cd ..

echo 'Creating source tarballs...'
tar cfz $repo-$version.tar.gz $repo-$version
tar cfj $repo-$version.tar.bz2 $repo-$version
7za a -bd -tzip $repo-$version.zip $repo-$version > /dev/null
7za a -bd $repo-$version.7z $repo-$version > /dev/null

echo "Release is in $tmp directory:"
ls -lh $tmp
chmod 644 $repo-$version.*

cd "$srcdir"

if [ $dotag -eq 1 ] ; then
    # Tag the release
    git tag -s -m "Tag release $version" "$version"
fi
